#!D:\mlops\deep-lerning_project\end_to_end_chest_classification_with_mlflow_and_dvc\cancer\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
